[workspace]
members = [".", "simsym-macros"]
resolver = "3"

[package]
name = "simsym"
version = "0.1.0"
edition = "2024"
description = "A simple symbolic computation library"
license = "BSD-3-Clause"

[dependencies]
num-integer = "0.1.46"
num-rational = "0.4.2"
num-traits = "0.2.19"
simsym-macros = { path = "simsym-macros" }
thiserror = "2.0.18"

serde = { version = "1.0.228", optional = true, features = ["derive"] }

[features]
default = ["simplify", "diff", "integrate"]
simplify = []
diff = []
integrate = ["diff"]
serde = ["dep:serde", "num-rational/serde"]
bigint = ["num-rational/num-bigint", "dep:num-bigint"]

[dependencies.num-bigint]
version = "0.4.6"
optional = true

[dev-dependencies]
proptest = "1.11.0"

[lib]
name = "simsym"
path = "src/lib.rs"

[[example]]
name = "calculus"
required-features = ["integrate", "diff", "simplify"]

[[example]]
name = "multivar"
required-features = ["diff", "simplify"]

[[example]]
name = "numeric_integral"
required-features = ["integrate"]

[[test]]
name = "proptest_diff"
required-features = ["diff", "simplify"]

[[test]]
name = "macro_test"
required-features = ["simplify", "integrate", "diff"]
